services:
  - type: web
    name: webturismo
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn webturismo.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"